export const USER_REGISTRATION = {
	ALREADY_EXIST: 'USER_REGISTRATION_ALREADY_EXIST',
	NOT_FOUND: 'USER_REGISTRATION_NOT_FOUND',
	EMAIL_OR_PASSWORD_ARE_INCORRECT: 'EMAIL_OR_PASSWORD_ARE_INCORRECT'
}

export const PERFIL_ERRORS = {
	ALREADY_EXIST: 'PERFIL_ALREADY_EXIST',
}

export const ACCOUNT_ERRORS = {
	ALREADY_EXIST_USER_RELATED: 'ACCOUNT_ALREADY_EXIST_USER_RELATED',
	NOT_ACCOUNT_RELATED_USER: 'ACCOUNT_NOT_ACCOUNT_RELATED_USER'

}

export const TRANSACTION_ERRORS = {
	NOT_FOUND: 'TRANSACTION_NOT_FOUND',
}

export const SERVER_ERRORS = {
	INTERNAL: 'INTERNAL_SERVER_ERROR'
}

export const AUTHENTICATION_ERRORS = {
	TOKEN_NOT_FOUND: 'AUTHENTICATION_TOKEN_NOT_FOUND',
	TOKEN_INVALID: 'AUTHENTICATION_TOKEN_INVALID',
	TOKEN_EXPIRED: 'AUTHENTICATION_TOKEN_EXPIRED',
	REFRASH_TOKEN_INVALID: 'AUTHENTICATION_REFRASH_TOKEN_INVALID'
}

