export const USER_REGISTRATION = {
	ALREADY_EXIST: 'USER_REGISTRATION_ALREADY_EXIST',
	NOT_FOUND: 'USER_REGISTRATION_NOT_FOUND',
	EMAIL_OR_PASSWORD_ARE_INCORRECT: 'EMAIL_OR_PASSWORD_ARE_INCORRECT'
}

export const PERFIL_ERRORS = {
	ALREADY_EXIST: 'PERFIL_ALREADY_EXIST',
}

export const ACCOUNT_ERRORS = {
	ALREADY_EXIST_USER_RELATED: 'ACCOUNT_ALREADY_EXIST_USER_RELATED',

}


export const SERVER_ERRORS = {
	INTERNAL: 'INTERNAL_SERVER_ERROR'
}